### ISSUE TITLE
No possibility to easily scale horizontally

### ISSUE THREAD

**Issue by janmyszkier** [spryker/docker-shop-suite#11]
The current docker approach which holds both nginx and FPM in same container will not allow easy scale.
Please separate those containers so it's possible to use `docker-compose scale php=3` and then reconfigure nginx to load balance between them by using `upstream` config

**Comment by tvaleriy** [comment]
Hi @janmyszkier, just accidentally got to this issue.
It's not an official Spryker's repository for a docker-based environment for development or production environments.
This is used internally but at the same time it is public repo for references to some parts of possible configurations for hosting providers.

Best,
Spryker Support Team
