### ISSUE TITLE
Relation does not exist errors during installation when starting containers

### ISSUE THREAD

**Issue by boersteken** [spryker/docker-shop-suite#29]
After starting the containers with `docker-compose up` the installer fails with multiple 

> relation "spy_event_behavior_entity_change" does not exist at character 223

errors until it finally aborts and exits.

> app_1            | 
> app_1            | Store: DE | Environment: staging
> app_1            | Clean schema directory
> app_1            | Copy and merge schema files
> app_1            | Create diff
> db_1             | ERROR:  relation "propel_migration" does not exist at character 21
> db_1             | STATEMENT:  SELECT version FROM propel_migration
> app_1            | 
> app_1            | In MigrationDiffCommand.php line 104:
> app_1            |                                                                                
> app_1            |   Uncommitted migrations have been found ; you should either execute or delet  
> app_1            |   e them before rerunning the 'diff' task                                      
> app_1            |                                                                                
> app_1            | 
> app_1            | migration:diff [--platform PLATFORM] [--config-dir CONFIG-DIR] [--recursive] [--schema-dir SCHEMA-DIR] [--output-dir OUTPUT-DIR] [--migration-table MIGRATION-TABLE] [--connection CONNECTION] [--table-renaming] [--editor [EDITOR]] [--skip-removed-table] [--skip-tables [SKIP-TABLES]] [--disable-identifier-quoting] [-m|--comment [COMMENT]] [--suffix [SUFFIX]]
> app_1            | 
> db_1             | ERROR:  relation "spy_event_behavior_entity_change" does not exist at character 223
> db_1             | STATEMENT:  SELECT "spy_event_behavior_entity_change"."id_event_behavior_entity_change", "spy_event_behavior_entity_change"."data", "spy_event_behavior_entity_change"."process_id", "spy_event_behavior_entity_change"."created_at" FROM "spy_event_behavior_entity_change" WHERE "spy_event_behavior_entity_change"."process_id"=$1 ORDER BY "spy_event_behavior_entity_change"."id_event_behavior_entity_change" ASC
> app_1            | 
> app_1            | In CommandLineExecutable.php line 101:
> app_1            |                                                 
> app_1            |   [Spryker\Install\Exception\InstallException]  
> app_1            |   Aborted install...                            
> app_1            |                                                 
> app_1            | 
> app_1            | Exception trace:
> app_1            |  () at /versions/2019-04-08_11-15/vendor/spryker/install/src/Spryker/Install/Executable/CommandLine/CommandLineExecutable.php:101
> app_1            |  Spryker\Install\Executable\CommandLine\CommandLineExecutable->abortInstallIfNotAllowedToContinue() at /versions/2019-04-08_11-15/vendor/spryker/install/src/Spryker/Install/Executable/CommandLine/CommandLineExecutable.php:57
> app_1            |  Spryker\Install\Executable\CommandLine\CommandLineExecutable->execute() at /versions/2019-04-08_11-15/vendor/spryker/install/src/Spryker/Install/Runner/Section/Command/CommandRunner.php:214
> app_1            |  Spryker\Install\Runner\Section\Command\CommandRunner->executeExecutable() at /versions/2019-04-08_11-15/vendor/spryker/install/src/Spryker/Install/Runner/Section/Command/CommandRunner.php:103
> app_1            |  Spryker\Install\Runner\Section\Command\CommandRunner->runCommand() at /versions/2019-04-08_11-15/vendor/spryker/install/src/Spryker/Install/Runner/Section/Command/CommandRunner.php:61
> app_1            |  Spryker\Install\Runner\Section\Command\CommandRunner->run() at /versions/2019-04-08_11-15/vendor/spryker/install/src/Spryker/Install/Runner/Section/SectionRunner.php:45
> app_1            |  Spryker\Install\Runner\Section\SectionRunner->run() at /versions/2019-04-08_11-15/vendor/spryker/install/src/Spryker/Install/Runner/InstallRunner.php:91
> app_1            |  Spryker\Install\Runner\InstallRunner->executeStage() at /versions/2019-04-08_11-15/vendor/spryker/install/src/Spryker/Install/Runner/InstallRunner.php:71
> app_1            |  Spryker\Install\Runner\InstallRunner->run() at /versions/2019-04-08_11-15/vendor/spryker/install/src/Spryker/Install/InstallFacade.php:25
> app_1            |  Spryker\Install\InstallFacade->runInstall() at /versions/2019-04-08_11-15/vendor/spryker/install/src/Spryker/Console/InstallConsoleCommand.php:118
> app_1            |  Spryker\Console\InstallConsoleCommand->execute() at /versions/2019-04-08_11-15/vendor/symfony/console/Command/Command.php:255
> app_1            |  Symfony\Component\Console\Command\Command->run() at /versions/2019-04-08_11-15/vendor/symfony/console/Application.php:960
> app_1            |  Symfony\Component\Console\Application->doRunCommand() at /versions/2019-04-08_11-15/vendor/symfony/console/Application.php:255
> app_1            |  Symfony\Component\Console\Application->doRun() at /versions/2019-04-08_11-15/vendor/symfony/console/Application.php:148
> app_1            |  Symfony\Component\Console\Application->run() at /versions/2019-04-08_11-15/vendor/spryker/install/bin/install:31
> app_1            | 
> app_1            | install [-r|--recipe RECIPE] [-d|--dry-run] [-s|--sections SECTIONS] [-g|--groups GROUPS] [-x|--exclude EXCLUDE] [-e|--include-excluded INCLUDE-EXCLUDED] [-i|--interactive] [-b|--breakpoint] [-a|--ask-before-continue] [-l|--log] [--] [<store>]
> app_1            | 
> spryker-docker_app_1 exited with code 1

**Comment by tvaleriy** [comment]
Hi @boersteken, just accidentally got to this issue.
It's not an official Spryker's repository for a docker-based environment for development or production.
This repo is used internally but at the same time it is public for references to some parts of configurations for hosting providers.

Best,
Spryker Support Team
